# Criteria 5: Profile-specific configuration file (1.5 pts)

# Criteria 4: Database Connection (H2 In-Memory DB) (1 pt)
spring.datasource.url=jdbc:h2:mem:blogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Criteria 2: Logging Configuration
# Default logging level (0.5 pts), Console logging happens automatically (0.5 pts)
logging.level.root=INFO
# Logging to file (1 pt)
logging.file.name=blog-application.log

# Criteria 5: Custom Configuration Parameters to be used with @Value (1.5 pts)
blog.name=My Awesome Java Blog
upload.directory=uploads/